### ISSUE TITLE
拖动RatingBar的时候，可以拖到0星，怎么禁止这种情况呢，我想最少要1星

### ISSUE THREAD

**Issue by hegaojian** [DreaminginCodeZH/MaterialRatingBar#31]

**Comment by zhanghai** [comment]
This is a generic problem about framework RatingBar, not specific to this library.

That being said, I would suggest trying the following solution:

https://stackoverflow.com/a/26360233/2420519

And you can try use the listener provided by this library instead, which will be called during dragging instead of after.

**Comment by hegaojian** [comment]
Thanks very much ,啦啦德玛西亚

**Comment by adustdu2015** [comment]
我想问一下，能不能只选择整数，不选半星。

**Comment by zhanghai** [comment]
@adustdu2015 #35

**Comment by hegaojian** [comment]
可以的，你设置增长数为1就好了  他默认好像是0.5

**Comment by adustdu2015** [comment]
thank you

**Comment by zwping** [comment]
@zhanghai 

``` kt
setOnRatingChangeListener { ratingBar, rating -> if (rating < 1) ratingBar.rating = 1F } // rating = 0
setOnRatingBarChangeListener { ratingBar, rating, fromUser -> if (rating < 1) ratingBar.rating = 1F } // 过后rating = 1生效
```

原本想通过上面的监听来实现该issues的目的，但setOnRatingChangeListener 刷新出现了bug，使用setOnRatingBarChangeListener 体验不佳，最终通过重写touch禁用拖动实现。
